exp_config_path = "../data/exp_config.json"
exp_config_temp_path = "../data/exp_config_temp.json"
dm_config_path = "../data/dataset_modifier.json"
dataset_variations_dir = "../data/dataset_variations"
matchings_dir = "../data/matchings"
